### ISSUE TITLE
Does `aarch64` binary exist?

### ISSUE THREAD

**Issue by SKevo18** [LittleBigBug/QuickBMS#4]
Is it possible to run QuickBMS on `aarch64` Ubuntu? The current codebase seems to compile for only 32-bit, correct?

https://github.com/LittleBigBug/QuickBMS/blob/5315ffe664b88dc09ae783ad17d9dfd252b1c927/src/Makefile#L2-L3

**Comment by Hubclone** [comment]
Good work ❤️❤️❤️❤️❤️❤️❤️

**Comment by SKevo18** [comment]
I have done research, and it seems that the owner had abandoned the development of this software. One would assume why that would be the case, and I respect that.

For anyone stumbling upon this thread in the future, you can use QEMU to allow the binary to run on `aarch64` (ARM). Ubuntu:

```
sudo apt update
sudo apt install qemu-user-static

sudo apt install binfmt-support # usually comes with qemu-user-static

sudo dpkg --add-architecture i386
sudo apt update
sudo apt install libc6:i386 libncurses5:i386 libstdc++6:i386
```

After running these commands, you should be able to run the Linux executables (you can download them from https://aluigi.altervista.org/papers/quickbms_linux.zip, or https://web.archive.org/web/20240127102431/https://aluigi.altervista.org/papers/quickbms_linux.zip)

**Comment by Hubclone** [comment]
Thank.s ❤️❤️❤️❤️❤️you are very intelligent 🤓🧠🧠🧠❤️❤️
